test:
  my_cool_feature:
    enabled: false

  another_feature:
    enabled: true

  admin_only_feature:
    admin:
      enabled: true

  all_but_user_feature:
    enabled: true
    user:
      enabled: false
